# Generated by Django 5.0 on 2024-10-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_invitation_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='is_used',
        ),
    ]
