# Generated by Django 5.0 on 2024-10-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_invitation_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='imgs_bucket',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
