# Generated by Django 5.0 on 2024-10-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_company_imgs_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('can_view_company', 'Can view a Company'), ('can_create_company', 'Can create a Company'), ('can_edit_company', 'Can edit a Company'), ('can_delete_company', 'Can delete a Company')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_user', 'Can view a User'), ('can_create_user', 'Can create a User'), ('can_edit_user', 'Can edit a User'), ('can_delete_user', 'Can delete a User')]},
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
