# Generated by Django 5.0 on 2024-12-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_user', "Can view User's details"), ('can_view_users', 'Can view Users list'), ('can_invite_user', 'Can invite a User'), ('can_edit_user', 'Can edit a User'), ('can_delete_user', 'Can delete a User'), ('can_disable_user', 'Can disable a User')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Staff', 'Staff'), ('SuperUser', 'SuperUser')], default='Normal'),
        ),
    ]
