# Generated by Django 5.0 on 2024-12-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_rename_user_type_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Staff', 'Staff'), ('SuperUser', 'Super User')], default='Normal'),
        ),
    ]
